global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # для macOS/Windows
        # на Linux — обычно 'host.docker.internal' не работает,
        # можно попробовать '172.17.0.1' или ip своей машины
