spring:
  application:
    name: tracing-demo

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    metrics:
      export:
        prometheus:
          enabled: true
    endpoint:
      prometheus:
        enabled: true